version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
      - pgdata1:/var/lib/postgresql/data


volumes:
   pgdata1: